--- name:TartanEvent
config:
  meta_filename: 'meta.yaml'
  event_camera_idx: '0'
  rgb_camera_idx: '1'
  events_pkgsize: 50000
  root_folder: '/data/storage/pellerito/carwelding/P003'
  output_folder: '/data/storage/pellerito/carwelding/P003_converted'
  images_folder: '/data/storage/pellerito/carwelding/P003/image_left'
  #disparity_events_folder: 'disparity/event'
  #disparity_images_folder: 'disparity/image'
  img_ts_filename: '/data/storage/pellerito/carwelding/P003/timestamps.txt'
  events_filename: '/data/storage/pellerito/carwelding/P003/events.h5'
  # imu_filename: 'imu_sync/left/imu.h5'
  # disparity_ts_filename: 'disparity/timestamps.txt'
  # cam_to_imu_filename: 'calibration/cam_to_imu.yaml'
  # cam_to_cam_filename: 'calibration/cam_to_cam.yaml'


